### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Flupke1979** [Low-Frequency/klipper_backup_script#1]
Hello,
When running the install script I get following error:

Checking for dierectories
Scripts folder already exists
Log folder already exists
Downloading backup script
./setup.sh: line 74: conditional binary operator expected
./setup.sh: line 74: syntax error near `/home/pi/scripts/klipper_backup_script'
./setup.sh: line 74: `if [[ ! d /home/pi/scripts/klipper_backup_script ]]'

I updated the raspberry but still the same.

Regards,
Kim

**Comment by Low-Frequency** [comment]
Thanks for the feedback.

I had a typo in the setup script. Should be fixed with the latest commit.
