### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by luco85** [Low-Frequency/klipper_backup_script#14]
Hi i have an error during installation. I have git at 2.32 version

after executing the installation script I have this error:

-bash: ./setup_klipper_backup.sh: No such file or directory

**Comment by Low-Frequency** [comment]
Hi,

I guess you used the one line command I put in the README.md to install the script. I overlooked one of the old filenames in that command from the previous version. I fixed the filenames in the command, so it should work now

**Comment by luco85** [comment]
Yes i followed the istructions on the main page of github. Ok i’ll retry tonorrow and let you know if it work!
Thanks

**Comment by luco85** [comment]
yea, now it work! thanks

**Comment by Low-Frequency** [comment]
No problem. Thanks for the feedback
