### ISSUE TITLE
Error fatal: invalid refspec ''

### ISSUE THREAD

**Issue by varazir** [Low-Frequency/klipper_backup_script#18]
[2023-05-11 18:29:23]: Pushing to GitHub repository
fatal: invalid refspec ''
[2023-05-11 18:29:23]: Deleting old logs
   [➔] Backup succeeded
I keep getting that. 

What I googled is to do a pull  so I tried a restore but it didn't help

**Comment by matyman1122** [comment]
Yes I am getting the same issue

**Comment by oogoom** [comment]
same here.  get the same succeeded message but it did not succeed.  manual git push works successfully.

**Comment by varazir** [comment]
> same here. get the same succeeded message but it did not succeed. manual git push works successfully.

How you do it manually ?

**Comment by oogoom** [comment]
> > same here. get the same succeeded message but it did not succeed. manual git push works successfully.
> 
> How you do it manually ?

1) cd into your config directory that was initialized for git.  if you installed this script properly, it should have done that for you.  make sure you changed something from the version currently on github.
2) type the following commands:
git add .
git commit -m "test update"
git push
3) check your github for updates.   

as a temporary fix, i created a shell script with those commands and have it run as a cron job.   but i'd like to be able to use this script again!  really like the simplicity of it

**Comment by MarcErasmus79** [comment]
[2023-05-15 18:58:55]: Backing /home/pi/klipper_config/ up to GitHub
[2023-05-15 18:58:55]: Adding changes to push
[2023-05-15 18:58:55]: Committing to GitHub repository
On branch main
Your branch is ahead of 'origin/main' by 8 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[2023-05-15 18:58:55]: Pushing to GitHub repository
fatal: invalid refspec ''
[2023-05-15 18:58:55]: Deleting old logs
   [➔] Backup succeeded

**Comment by varazir** [comment]
Looks like it's working now. thanks  I still get the error but file are updated.

**Comment by matyman1122** [comment]
I was able to resolve this error by making a small tweak to the lib/functions/github_functions.sh file

in the backup_config_folders()  section I changed

git -C "${FOLDER}" push -u origin "${BRANCH}" | tee -a "${HOME}/kgb-log/$(date +%F).log"

to

git -C "${FOLDER}" push | tee -a "${HOME}/kgb-log/$(date +%F).log"

by not specifying the origin it will just use the default branch which should be fine.

**Comment by oogoom** [comment]
> I was able to resolve this error by making a small tweak to the lib/functions/github_functions.sh file
> 
> in the backup_config_folders() section I changed
> 
> git -C "${FOLDER}" push -u origin "${BRANCH}" | tee -a "${HOME}/kgb-log/$(date +%F).log"
> 
> to
> 
> git -C "${FOLDER}" push | tee -a "${HOME}/kgb-log/$(date +%F).log"
> 
> by not specifying the origin it will just use the default branch which should be fine.


This seems to work now.  nice going.  hopefully the scheduled backup succeeds the same way.

**Comment by matyman1122** [comment]
> This seems to work now. nice going. hopefully the scheduled backup succeeds the same way.

Thanks it was your comment that led me to the solution

**Comment by varazir** [comment]
> > This seems to work now. nice going. hopefully the scheduled backup succeeds the same way.
> 
> Thanks it was your comment that led me to the solution



> > I was able to resolve this error by making a small tweak to the lib/functions/github_functions.sh file
> > in the backup_config_folders() section I changed
> > git -C "${FOLDER}" push -u origin "${BRANCH}" | tee -a "${HOME}/kgb-log/$(date +%F).log"
> > to
> > git -C "${FOLDER}" push | tee -a "${HOME}/kgb-log/$(date +%F).log"
> > by not specifying the origin it will just use the default branch which should be fine.
> 
> This seems to work now. nice going. hopefully the scheduled backup succeeds the same way.

If you don't want to change the script just change the conf file in ~/.config/kgb.cfg
GITHUB_BRANCH="main"
to 
BRANCH="main"

Branch was added in a pull request and the variables isn't matching. 

Should be a install script changing the chmod on the files

**Comment by matyman1122** [comment]
Makes sense! Good pickup

**Comment by varazir** [comment]
Added a pull request to change the variable. #20

**Comment by drkpxl** [comment]
Worked for me, thanks for this.

**Comment by Technofrikus** [comment]
> Added a pull request to change the variable. #20

Seems it was not accepted yet? 

I changed the line like in your PR by hand and now it finally works again. Thanks a lot!

**Comment by varazir** [comment]
> > Added a pull request to change the variable. #20
> 
> Seems it was not accepted yet?
> 
> I changed the line like in your PR by hand and now it finally works again. Thanks a lot!

Cool, you could just do a git pull from my repo. 

Btw have got the schedule to work?
If i run the backup.sh manually  it stops when I say deleting logs. I have to ctrl+c.

**Comment by Technofrikus** [comment]
> Btw have got the schedule to work? If i run the backup.sh manually it stops when I say deleting logs. I have to ctrl+c.
I reinstalled it today, so not sure if the schedule still works. But until now it worked, had 25 commits, only the pushing did not work. I only tried it by hand from the configuration interface. Not from terminal. But didnt do anything special to make it work. It just did.

**Comment by varazir** [comment]
> > Btw have got the schedule to work? If i run the backup.sh manually it stops when I say deleting logs. I have to ctrl+c.
> > I reinstalled it today, so not sure if the schedule still works. But until now it worked, had 25 commits, only the pushing did not work. I only tried it by hand from the configuration interface. Not from terminal. But didnt do anything special to make it work. It just did.

I have set iu like this but it's not doing any backups, 

![image](https://github.com/Low-Frequency/Klipper-Git-Backup/assets/262588/d1ad148d-504b-4d59-9823-841aba44d3fb)

**Comment by 5teveO** [comment]
> > > Btw have got the schedule to work? If i run the backup.sh manually it stops when I say deleting logs. I have to ctrl+c.
> > > I reinstalled it today, so not sure if the schedule still works. But until now it worked, had 25 commits, only the pushing did not work. I only tried it by hand from the configuration interface. Not from terminal. But didnt do anything special to make it work. It just did.
> 
> I have set iu like this but it's not doing any backups,
> 
> ![image](https://user-images.githubusercontent.com/262588/256971947-d1ad148d-504b-4d59-9823-841aba44d3fb.png)

I seem to be having the same issue as well. works with a manual backup but not set with time. One machine works - the other doesnt! Any ideas where to look?

**Comment by varazir** [comment]
> 

I haven't looked how it works at all. It has to run some type of daemon or something.

**Comment by Low-Frequency** [comment]
Sorry at all, that I abandoned this project for quite some time. I was getting burned out and had to take a break. Maybe I should at least have paid attention to my mails in the meantime.

Thanks @varazir for finding and fixing the issue. That must have been a remnant from the early days of the script which I overlooked.

Also apparently I missed some error handling in the backup function which caused the success message to appear, even when the `git push` failed. I think I'll address this in a later version.

Concerning the schedule:
Running `backup.sh` manually will end up in an endless loop if you have scheduled backups enabled. This is by design, since the utility is meant to be run as a service. You can check the status with `systemctl status kgb.service`, stop it via `systemctl stop kgb.service` and start it via `systemctl start kgb.service`. The service is set up in a way that it starts when the Pi boots, so you don't have to worry about ever starting it manually.

**Comment by Low-Frequency** [comment]
I took a look at the code again and fixed the backup function not recognizing errors. It should now log the errors and also print errors to stdout when executed manually.

Also I moved from an inconsistent endless loop for the scheduled backups to systemd timers like suggested in #19. It's not tested yet, but anybody who want's to try it can pull the code from the dev branch.
