### ISSUE TITLE
systemd timer vs sleep

### ISSUE THREAD

**Issue by chasebolt** [Low-Frequency/klipper_backup_script#19]
systemd timer would be a better implementation versus sleep. sleeping is inconsistent when a user restarts the device. 

for example, the backup runs daily and should run within the hour but I decide I need to restart my pi. the sleep will start over on startup and will miss the original backup time to run.

i propose a systemd timer is installed instead during the install process.

**Comment by Low-Frequency** [comment]
That is indeed a nice improvement. I just implemented that in the dev branch, but have to test it still.
