### ISSUE TITLE
Problem with systemctl timers

### ISSUE THREAD

**Issue by varazir** [Low-Frequency/klipper_backup_script#27]
I have set it up to run every day but when I checked no timer is listed. 

`pi@mainsailbx:~/Klipper-Git-Backup $ systemctl list-timers kgbsudo
NEXT LEFT LAST PASSED UNIT ACTIVATES

0 timers listed.
Pass --all to see loaded but inactive timers, too.`

when I list all timers I get this 

systemctl list-timers --all
NEXT                         LEFT          LAST                        PASSED       UNIT                         ACTIVATES
Sun 2024-03-24 15:30:45 CET  5h 12min left Sun 2024-03-24 01:54:44 CET 8h ago       apt-daily.timer              apt-daily.service
Sun 2024-03-24 17:09:50 CET  6h left       Sat 2024-03-23 17:09:50 CET 17h ago      systemd-tmpfiles-clean.timer systemd-tmpfiles-clea>
Mon 2024-03-25 00:00:00 CET  13h left      Sun 2024-03-24 00:00:50 CET 10h ago      logrotate.timer              logrotate.service
Mon 2024-03-25 00:00:00 CET  13h left      Sun 2024-03-24 00:00:50 CET 10h ago      man-db.timer                 man-db.service
Mon 2024-03-25 00:47:39 CET  14h left      Mon 2024-03-18 00:17:50 CET 6 days ago   fstrim.timer                 fstrim.service
Mon 2024-03-25 06:29:40 CET  20h left      Sun 2024-03-24 06:01:44 CET 4h 16min ago apt-daily-upgrade.timer      apt-daily-upgrade.ser>
Sun 2024-03-31 03:10:10 CEST 6 days left   Sun 2024-03-24 03:10:44 CET 7h ago       e2scrub_all.timer            e2scrub_all.service

I tried to change the settings , save and install, didn't help

**Comment by Low-Frequency** [comment]
I couldn't reproduce this issue during my tests, so the install works fine. If this happens with the new version just let me know and I'll investigate it further.
