### ISSUE TITLE
error message when running update script

### ISSUE THREAD

**Issue by stephbellemare** [Low-Frequency/klipper_backup_script#5]
When running the update_bak_util script receiving error message

> From https://github.com/Low-Frequency/klipper_backup_script
>  * branch            main       -> FETCH_HEAD
> Already up to date.
> Checking your config

> /usr/local/bin/update_bak_util: line 65: syntax error near unexpected token `fi'

> /usr/local/bin/update_bak_util: line 65: `fi'

running script from home dir.
(sorry i cannot seem to be able to split the above on 2 lines)

**Comment by Low-Frequency** [comment]
Thanks for the feedback.

It should be fixed now.

I haven't had the time though to implement the repo option that was added to the update script, so be aware that you have to manually add that to your config after updating
