### ISSUE TITLE
setup.sh script not working

### ISSUE THREAD

**Issue by computergeek1507** [Low-Frequency/klipper_backup_script#8]
When trying to run the setup.sh, I get an error "git_repo.sh: line 25: syntax error near unexpected token `)'" I compiled and installed git version 2.36.1.

![image](https://user-images.githubusercontent.com/2293065/170847635-bfa48a40-0215-4f4f-9c07-d1ea5ced57ac.png)

**Comment by Low-Frequency** [comment]
Hi,

thanks for the feedback.
It was a minor syntax error. It should be fixed now.
