### ISSUE TITLE
Error if backup is run from terminal

### ISSUE THREAD

**Issue by allenrowand** [Low-Frequency/klipper_backup_script#9]
If I run the backup command from a terminal, it appears to back up but then I get a loop of:

nothing to commit, working tree clean
[2022-08-26 20:11:24]: Pushing
Everything up-to-date
branch 'main' set up to track 'origin/main'.
[2022-08-26 20:11:25]: Deleting old logs
/usr/local/bin/backup: line 144: [: =: unary operator expected
[2022-08-26 20:11:26]: Backing up to GitHub
[2022-08-26 20:11:26]: Adding changes to push
[2022-08-26 20:11:26]: Committing to GitHub repository
On branch main
Your branch is up to date with 'origin/main'.

Please let me know what additional information you need. Thanks!

**Comment by Low-Frequency** [comment]
Hi,

thanks for the output of the command. That helped finding a small syntax error.
Try reinstalling the utility. The syntax fix I just committed should fix your problem.

**Comment by allenrowand** [comment]
That did the trick, thanks!
